databases:
  - name: Bravo
    user: Bravo
    plan: free
    region: oregon

services:
  - type: web
    name: Bravo
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Bravo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REACT_APP_MAPS_API_KEY
        sync: false